server.port=8082

# JWT Properties
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000

# User Service URL
user-service.url=http://${USER_SERVICE_HOST:localhost}:${USER_SERVICE_PORT:8081}/api/users


spring.datasource.url=jdbc:postgresql://localhost:5432/user_db
spring.datasource.username=root
spring.datasource.password=root
